spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_app
    username:
    password:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
#    baseline-on-migrate: true
    locations: classpath:/db/migration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format.sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

exchange-rate-service:
  fixer:
    name: fixer
    api-key:
    base-url: http://data.fixer.io
    api-path: /api/latest
    logger-level: FULL